/**
 * Auto-generated from 标签库/刑法标签库.txt.
 * Level mapping:
 * - L1: 第X章
 * - L2: 第X节
 * - L3: 序号+罪名（1. / 序号列）
 * Root label is "刑事案由".
 */
export type CriminalCauseNode = {
  id: string;
  level: 1 | 2 | 3;
  label: string;
  parentId: string | null;
  path: string[];
  chapterIndex?: number;
  sectionIndex?: number;
  itemIndex?: number;
};

export const CRIMINAL_CAUSE_ROOT_LABEL = "刑事案由";

export const CRIMINAL_CAUSE_LIBRARY: CriminalCauseNode[] = [
  { id: "criminal-l1-1", level: 1, label: "危害国家安全罪", parentId: null, path: ["刑事案由", "危害国家安全罪"], chapterIndex: 1 },
  { id: "criminal-l3-1-0-1", level: 3, label: "背叛国家罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "背叛国家罪"], chapterIndex: 1, itemIndex: 1 },
  { id: "criminal-l3-1-0-2", level: 3, label: "分裂国家罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "分裂国家罪"], chapterIndex: 1, itemIndex: 2 },
  { id: "criminal-l3-1-0-3", level: 3, label: "煽动分裂国家罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "煽动分裂国家罪"], chapterIndex: 1, itemIndex: 3 },
  { id: "criminal-l3-1-0-4", level: 3, label: "武装叛乱、暴乱罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "武装叛乱、暴乱罪"], chapterIndex: 1, itemIndex: 4 },
  { id: "criminal-l3-1-0-5", level: 3, label: "颠覆国家政权罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "颠覆国家政权罪"], chapterIndex: 1, itemIndex: 5 },
  { id: "criminal-l3-1-0-6", level: 3, label: "煽动颠覆国家政权罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "煽动颠覆国家政权罪"], chapterIndex: 1, itemIndex: 6 },
  { id: "criminal-l3-1-0-7", level: 3, label: "资助危害国家安全犯罪活动罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "资助危害国家安全犯罪活动罪"], chapterIndex: 1, itemIndex: 7 },
  { id: "criminal-l3-1-0-8", level: 3, label: "投敌叛变罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "投敌叛变罪"], chapterIndex: 1, itemIndex: 8 },
  { id: "criminal-l3-1-0-9", level: 3, label: "叛逃罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "叛逃罪"], chapterIndex: 1, itemIndex: 9 },
  { id: "criminal-l3-1-0-10", level: 3, label: "间谍罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "间谍罪"], chapterIndex: 1, itemIndex: 10 },
  { id: "criminal-l3-1-0-11", level: 3, label: "为境外窃取、剌探、收买、非法提供国家秘密、情报罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "为境外窃取、剌探、收买、非法提供国家秘密、情报罪"], chapterIndex: 1, itemIndex: 11 },
  { id: "criminal-l3-1-0-12", level: 3, label: "资敌罪", parentId: "criminal-l1-1", path: ["刑事案由", "危害国家安全罪", "资敌罪"], chapterIndex: 1, itemIndex: 12 },
  { id: "criminal-l1-2", level: 1, label: "危害公共安全罪", parentId: null, path: ["刑事案由", "危害公共安全罪"], chapterIndex: 2 },
  { id: "criminal-l3-2-0-13", level: 3, label: "放火罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "放火罪"], chapterIndex: 2, itemIndex: 13 },
  { id: "criminal-l3-2-0-14", level: 3, label: "决水罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "决水罪"], chapterIndex: 2, itemIndex: 14 },
  { id: "criminal-l3-2-0-15", level: 3, label: "爆炸罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "爆炸罪"], chapterIndex: 2, itemIndex: 15 },
  { id: "criminal-l3-2-0-16", level: 3, label: "投放危险物质罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "投放危险物质罪"], chapterIndex: 2, itemIndex: 16 },
  { id: "criminal-l3-2-0-17", level: 3, label: "以危险方法危害公共安全罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "以危险方法危害公共安全罪"], chapterIndex: 2, itemIndex: 17 },
  { id: "criminal-l3-2-0-18", level: 3, label: "失火罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "失火罪"], chapterIndex: 2, itemIndex: 18 },
  { id: "criminal-l3-2-0-19", level: 3, label: "过失决水罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失决水罪"], chapterIndex: 2, itemIndex: 19 },
  { id: "criminal-l3-2-0-20", level: 3, label: "过失爆炸罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失爆炸罪"], chapterIndex: 2, itemIndex: 20 },
  { id: "criminal-l3-2-0-21", level: 3, label: "过失投放危险物质罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失投放危险物质罪"], chapterIndex: 2, itemIndex: 21 },
  { id: "criminal-l3-2-0-22", level: 3, label: "过失以危险方法危害公共安全罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失以危险方法危害公共安全罪"], chapterIndex: 2, itemIndex: 22 },
  { id: "criminal-l3-2-0-23", level: 3, label: "破坏交通工具罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "破坏交通工具罪"], chapterIndex: 2, itemIndex: 23 },
  { id: "criminal-l3-2-0-24", level: 3, label: "破坏交通设施罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "破坏交通设施罪"], chapterIndex: 2, itemIndex: 24 },
  { id: "criminal-l3-2-0-25", level: 3, label: "破坏电力设备罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "破坏电力设备罪"], chapterIndex: 2, itemIndex: 25 },
  { id: "criminal-l3-2-0-26", level: 3, label: "破坏易燃易爆设备罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "破坏易燃易爆设备罪"], chapterIndex: 2, itemIndex: 26 },
  { id: "criminal-l3-2-0-27", level: 3, label: "过失损坏交通工具罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失损坏交通工具罪"], chapterIndex: 2, itemIndex: 27 },
  { id: "criminal-l3-2-0-28", level: 3, label: "过失损坏交通设施罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失损坏交通设施罪"], chapterIndex: 2, itemIndex: 28 },
  { id: "criminal-l3-2-0-29", level: 3, label: "过失损坏电力设备罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失损坏电力设备罪"], chapterIndex: 2, itemIndex: 29 },
  { id: "criminal-l3-2-0-30", level: 3, label: "过失损坏易燃易爆设备罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失损坏易燃易爆设备罪"], chapterIndex: 2, itemIndex: 30 },
  { id: "criminal-l3-2-0-31", level: 3, label: "组织、领导、参加恐怖组织罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "组织、领导、参加恐怖组织罪"], chapterIndex: 2, itemIndex: 31 },
  { id: "criminal-l3-2-0-32", level: 3, label: "帮助恐怖活动罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "帮助恐怖活动罪"], chapterIndex: 2, itemIndex: 32 },
  { id: "criminal-l3-2-0-33", level: 3, label: "准备实施恐怖活动罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "准备实施恐怖活动罪"], chapterIndex: 2, itemIndex: 33 },
  { id: "criminal-l3-2-0-34", level: 3, label: "宣扬恐怖主义、极端主义、煽动实施恐怖活动罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "宣扬恐怖主义、极端主义、煽动实施恐怖活动罪"], chapterIndex: 2, itemIndex: 34 },
  { id: "criminal-l3-2-0-35", level: 3, label: "利用极端主义破坏法律实施罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "利用极端主义破坏法律实施罪"], chapterIndex: 2, itemIndex: 35 },
  { id: "criminal-l3-2-0-36", level: 3, label: "强制穿戴宣扬恐怖主义、极端主义服饰、标志罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "强制穿戴宣扬恐怖主义、极端主义服饰、标志罪"], chapterIndex: 2, itemIndex: 36 },
  { id: "criminal-l3-2-0-37", level: 3, label: "非法持有宣扬恐怖主义、极端主义物品罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "非法持有宣扬恐怖主义、极端主义物品罪"], chapterIndex: 2, itemIndex: 37 },
  { id: "criminal-l3-2-0-38", level: 3, label: "劫持航空器罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "劫持航空器罪"], chapterIndex: 2, itemIndex: 38 },
  { id: "criminal-l3-2-0-39", level: 3, label: "劫持船只、汽车罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "劫持船只、汽车罪"], chapterIndex: 2, itemIndex: 39 },
  { id: "criminal-l3-2-0-40", level: 3, label: "暴力危及飞行安全罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "暴力危及飞行安全罪"], chapterIndex: 2, itemIndex: 40 },
  { id: "criminal-l3-2-0-41", level: 3, label: "破坏广播电视设施、公用电信设施罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "破坏广播电视设施、公用电信设施罪"], chapterIndex: 2, itemIndex: 41 },
  { id: "criminal-l3-2-0-42", level: 3, label: "过失损坏广播电视设施、公用电信设施罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "过失损坏广播电视设施、公用电信设施罪"], chapterIndex: 2, itemIndex: 42 },
  { id: "criminal-l3-2-0-43", level: 3, label: "非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "非法制造、买卖、运输、邮寄、储存枪支、弹药、爆炸物罪"], chapterIndex: 2, itemIndex: 43 },
  { id: "criminal-l3-2-0-44", level: 3, label: "非法制造、买卖、运输、储存危险物质罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "非法制造、买卖、运输、储存危险物质罪"], chapterIndex: 2, itemIndex: 44 },
  { id: "criminal-l3-2-0-45", level: 3, label: "违规制造、销售枪支罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "违规制造、销售枪支罪"], chapterIndex: 2, itemIndex: 45 },
  { id: "criminal-l3-2-0-46", level: 3, label: "盗窃、抢夺枪支、弹药、爆炸物、危险物质罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "盗窃、抢夺枪支、弹药、爆炸物、危险物质罪"], chapterIndex: 2, itemIndex: 46 },
  { id: "criminal-l3-2-0-47", level: 3, label: "抢劫枪支、弹药、爆炸物、危险物质罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "抢劫枪支、弹药、爆炸物、危险物质罪"], chapterIndex: 2, itemIndex: 47 },
  { id: "criminal-l3-2-0-48", level: 3, label: "非法持有、私藏枪支、弹药罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "非法持有、私藏枪支、弹药罪"], chapterIndex: 2, itemIndex: 48 },
  { id: "criminal-l3-2-0-49", level: 3, label: "非法出租、出借枪支罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "非法出租、出借枪支罪"], chapterIndex: 2, itemIndex: 49 },
  { id: "criminal-l3-2-0-50", level: 3, label: "丢失枪支不报罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "丢失枪支不报罪"], chapterIndex: 2, itemIndex: 50 },
  { id: "criminal-l3-2-0-51", level: 3, label: "非法携带枪支、弹药、管制刀具、危险物品危及公共安全罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "非法携带枪支、弹药、管制刀具、危险物品危及公共安全罪"], chapterIndex: 2, itemIndex: 51 },
  { id: "criminal-l3-2-0-52", level: 3, label: "重大飞行事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "重大飞行事故罪"], chapterIndex: 2, itemIndex: 52 },
  { id: "criminal-l3-2-0-53", level: 3, label: "铁路运营安全事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "铁路运营安全事故罪"], chapterIndex: 2, itemIndex: 53 },
  { id: "criminal-l3-2-0-54", level: 3, label: "交通肇事罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "交通肇事罪"], chapterIndex: 2, itemIndex: 54 },
  { id: "criminal-l3-2-0-55", level: 3, label: "危险驾驶罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "危险驾驶罪"], chapterIndex: 2, itemIndex: 55 },
  { id: "criminal-l3-2-0-56", level: 3, label: "妨害安全驾驶罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "妨害安全驾驶罪"], chapterIndex: 2, itemIndex: 56 },
  { id: "criminal-l3-2-0-57", level: 3, label: "重大责任事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "重大责任事故罪"], chapterIndex: 2, itemIndex: 57 },
  { id: "criminal-l3-2-0-58", level: 3, label: "强令、组织他人违章冒险作业罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "强令、组织他人违章冒险作业罪"], chapterIndex: 2, itemIndex: 58 },
  { id: "criminal-l3-2-0-59", level: 3, label: "危险作业罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "危险作业罪"], chapterIndex: 2, itemIndex: 59 },
  { id: "criminal-l3-2-0-60", level: 3, label: "重大劳动安全事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "重大劳动安全事故罪"], chapterIndex: 2, itemIndex: 60 },
  { id: "criminal-l3-2-0-61", level: 3, label: "大型群众性活动重大安全事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "大型群众性活动重大安全事故罪"], chapterIndex: 2, itemIndex: 61 },
  { id: "criminal-l3-2-0-62", level: 3, label: "危险物品肇事罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "危险物品肇事罪"], chapterIndex: 2, itemIndex: 62 },
  { id: "criminal-l3-2-0-63", level: 3, label: "工程重大安全事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "工程重大安全事故罪"], chapterIndex: 2, itemIndex: 63 },
  { id: "criminal-l3-2-0-64", level: 3, label: "教育设施重大安全事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "教育设施重大安全事故罪"], chapterIndex: 2, itemIndex: 64 },
  { id: "criminal-l3-2-0-65", level: 3, label: "消防责任事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "消防责任事故罪"], chapterIndex: 2, itemIndex: 65 },
  { id: "criminal-l3-2-0-66", level: 3, label: "不报、谎报安全事故罪", parentId: "criminal-l1-2", path: ["刑事案由", "危害公共安全罪", "不报、谎报安全事故罪"], chapterIndex: 2, itemIndex: 66 },
  { id: "criminal-l1-3", level: 1, label: "破坏社会主义市场经济秩序罪", parentId: null, path: ["刑事案由", "破坏社会主义市场经济秩序罪"], chapterIndex: 3 },
  { id: "criminal-l2-3-1", level: 2, label: "生产、销售伪劣商品罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪"], chapterIndex: 3, sectionIndex: 1 },
  { id: "criminal-l3-3-1-67", level: 3, label: "生产、销售伪劣产品罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售伪劣产品罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 67 },
  { id: "criminal-l3-3-1-68", level: 3, label: "生产、销售、提供假药罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售、提供假药罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 68 },
  { id: "criminal-l3-3-1-69", level: 3, label: "生产、销售、提供劣药罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售、提供劣药罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 69 },
  { id: "criminal-l3-3-1-70", level: 3, label: "妨害药品管理罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "妨害药品管理罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 70 },
  { id: "criminal-l3-3-1-71", level: 3, label: "生产、销售不符合安全标准的食品罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售不符合安全标准的食品罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 71 },
  { id: "criminal-l3-3-1-72", level: 3, label: "生产、销售有毒、有害食品罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售有毒、有害食品罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 72 },
  { id: "criminal-l3-3-1-73", level: 3, label: "生产、销售不符合标准的医用器材罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售不符合标准的医用器材罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 73 },
  { id: "criminal-l3-3-1-74", level: 3, label: "生产、销售不符合安全标准的产品罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售不符合安全标准的产品罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 74 },
  { id: "criminal-l3-3-1-75", level: 3, label: "生产、销售伪劣农药、兽药、化肥、种子罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售伪劣农药、兽药、化肥、种子罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 75 },
  { id: "criminal-l3-3-1-76", level: 3, label: "生产、销售不符合卫生标准的化妆品罪", parentId: "criminal-l2-3-1", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "生产、销售伪劣商品罪", "生产、销售不符合卫生标准的化妆品罪"], chapterIndex: 3, sectionIndex: 1, itemIndex: 76 },
  { id: "criminal-l2-3-2", level: 2, label: "走私罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪"], chapterIndex: 3, sectionIndex: 2 },
  { id: "criminal-l3-3-2-77", level: 3, label: "走私武器、弹药罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私武器、弹药罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 77 },
  { id: "criminal-l3-3-2-78", level: 3, label: "走私核材料罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私核材料罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 78 },
  { id: "criminal-l3-3-2-79", level: 3, label: "走私假币罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私假币罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 79 },
  { id: "criminal-l3-3-2-80", level: 3, label: "走私文物罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私文物罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 80 },
  { id: "criminal-l3-3-2-81", level: 3, label: "走私贵重金属罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私贵重金属罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 81 },
  { id: "criminal-l3-3-2-82", level: 3, label: "走私珍贵动物、珍贵动物制品罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私珍贵动物、珍贵动物制品罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 82 },
  { id: "criminal-l3-3-2-83", level: 3, label: "走私国家禁止进出口的货物、物品罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私国家禁止进出口的货物、物品罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 83 },
  { id: "criminal-l3-3-2-84", level: 3, label: "走私淫秽物品罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私淫秽物品罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 84 },
  { id: "criminal-l3-3-2-85", level: 3, label: "走私废物罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私废物罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 85 },
  { id: "criminal-l3-3-2-86", level: 3, label: "走私普通货物、物品罪", parentId: "criminal-l2-3-2", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "走私罪", "走私普通货物、物品罪"], chapterIndex: 3, sectionIndex: 2, itemIndex: 86 },
  { id: "criminal-l2-3-3", level: 2, label: "妨害对公司、企业的管理秩序罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪"], chapterIndex: 3, sectionIndex: 3 },
  { id: "criminal-l3-3-3-87", level: 3, label: "虚报注册资本罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "虚报注册资本罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 87 },
  { id: "criminal-l3-3-3-88", level: 3, label: "虚假出资、抽逃出资罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "虚假出资、抽逃出资罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 88 },
  { id: "criminal-l3-3-3-89", level: 3, label: "欺诈发行证券罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "欺诈发行证券罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 89 },
  { id: "criminal-l3-3-3-90", level: 3, label: "违规披露、不披露重要信息罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "违规披露、不披露重要信息罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 90 },
  { id: "criminal-l3-3-3-91", level: 3, label: "妨害清算罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "妨害清算罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 91 },
  { id: "criminal-l3-3-3-92", level: 3, label: "隐匿、故意销毁会计凭证、会计帐簿、财务会计报告罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "隐匿、故意销毁会计凭证、会计帐簿、财务会计报告罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 92 },
  { id: "criminal-l3-3-3-93", level: 3, label: "虚假破产罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "虚假破产罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 93 },
  { id: "criminal-l3-3-3-94", level: 3, label: "非国家工作人员受贿罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "非国家工作人员受贿罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 94 },
  { id: "criminal-l3-3-3-95", level: 3, label: "对非国家工作人员行贿罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "对非国家工作人员行贿罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 95 },
  { id: "criminal-l3-3-3-96", level: 3, label: "对外国公职人员、国际公共组织官员行贿罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "对外国公职人员、国际公共组织官员行贿罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 96 },
  { id: "criminal-l3-3-3-97", level: 3, label: "非法经营同类营业罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "非法经营同类营业罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 97 },
  { id: "criminal-l3-3-3-98", level: 3, label: "为亲友非法牟利罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "为亲友非法牟利罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 98 },
  { id: "criminal-l3-3-3-99", level: 3, label: "签订、履行合同失职被骗罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "签订、履行合同失职被骗罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 99 },
  { id: "criminal-l3-3-3-100", level: 3, label: "国有公司、企业、事业单位人员失职罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "国有公司、企业、事业单位人员失职罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 100 },
  { id: "criminal-l3-3-3-101", level: 3, label: "国有公司、企业、事业单位人员滥用职权罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "国有公司、企业、事业单位人员滥用职权罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 101 },
  { id: "criminal-l3-3-3-102", level: 3, label: "徇私舞弊低价折股、出售国有资产罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "徇私舞弊低价折股、出售国有资产罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 102 },
  { id: "criminal-l3-3-3-103", level: 3, label: "背信损害上市公司利益罪", parentId: "criminal-l2-3-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "妨害对公司、企业的管理秩序罪", "背信损害上市公司利益罪"], chapterIndex: 3, sectionIndex: 3, itemIndex: 103 },
  { id: "criminal-l2-3-4", level: 2, label: "破坏金融管理秩序罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪"], chapterIndex: 3, sectionIndex: 4 },
  { id: "criminal-l3-3-4-104", level: 3, label: "伪造货币罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "伪造货币罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 104 },
  { id: "criminal-l3-3-4-105", level: 3, label: "出售、购买、运输假币罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "出售、购买、运输假币罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 105 },
  { id: "criminal-l3-3-4-106", level: 3, label: "金融工作人员购买假币、以假币换取货币罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "金融工作人员购买假币、以假币换取货币罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 106 },
  { id: "criminal-l3-3-4-107", level: 3, label: "持有、使用假币罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "持有、使用假币罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 107 },
  { id: "criminal-l3-3-4-108", level: 3, label: "变造货币罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "变造货币罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 108 },
  { id: "criminal-l3-3-4-109", level: 3, label: "擅自设立金融机构罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "擅自设立金融机构罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 109 },
  { id: "criminal-l3-3-4-110", level: 3, label: "伪造、变造、转让金融机构经营许可证、批准文件罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "伪造、变造、转让金融机构经营许可证、批准文件罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 110 },
  { id: "criminal-l3-3-4-111", level: 3, label: "高利转贷罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "高利转贷罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 111 },
  { id: "criminal-l3-3-4-112", level: 3, label: "骗取贷款、票据承兑、金融票证罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "骗取贷款、票据承兑、金融票证罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 112 },
  { id: "criminal-l3-3-4-113", level: 3, label: "非法吸收公众存款罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "非法吸收公众存款罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 113 },
  { id: "criminal-l3-3-4-114", level: 3, label: "伪造、变造金融票证罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "伪造、变造金融票证罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 114 },
  { id: "criminal-l3-3-4-115", level: 3, label: "妨害信用卡管理罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "妨害信用卡管理罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 115 },
  { id: "criminal-l3-3-4-116", level: 3, label: "窃取、收买、非法提供信用卡信息罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "窃取、收买、非法提供信用卡信息罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 116 },
  { id: "criminal-l3-3-4-117", level: 3, label: "伪造、变造国家有价证券罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "伪造、变造国家有价证券罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 117 },
  { id: "criminal-l3-3-4-118", level: 3, label: "伪造、变造股票、公司、企业债券罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "伪造、变造股票、公司、企业债券罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 118 },
  { id: "criminal-l3-3-4-119", level: 3, label: "擅自发行股票、公司、企业债券罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "擅自发行股票、公司、企业债券罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 119 },
  { id: "criminal-l3-3-4-120", level: 3, label: "内幕交易、泄露内幕信息罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "内幕交易、泄露内幕信息罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 120 },
  { id: "criminal-l3-3-4-121", level: 3, label: "利用未公开信息交易罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "利用未公开信息交易罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 121 },
  { id: "criminal-l3-3-4-122", level: 3, label: "编造并传播证券、期货交易虚假信息罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "编造并传播证券、期货交易虚假信息罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 122 },
  { id: "criminal-l3-3-4-123", level: 3, label: "诱骗投资者买卖证券、期货合约罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "诱骗投资者买卖证券、期货合约罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 123 },
  { id: "criminal-l3-3-4-124", level: 3, label: "操纵证券、期货市场罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "操纵证券、期货市场罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 124 },
  { id: "criminal-l3-3-4-125", level: 3, label: "背信运用受托财产罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "背信运用受托财产罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 125 },
  { id: "criminal-l3-3-4-126", level: 3, label: "违法运用资金罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "违法运用资金罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 126 },
  { id: "criminal-l3-3-4-127", level: 3, label: "违法发放贷款罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "违法发放贷款罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 127 },
  { id: "criminal-l3-3-4-128", level: 3, label: "吸收客户资金不入账罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "吸收客户资金不入账罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 128 },
  { id: "criminal-l3-3-4-129", level: 3, label: "违规出具金融票证罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "违规出具金融票证罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 129 },
  { id: "criminal-l3-3-4-130", level: 3, label: "对违法票据承兑、付款、保证罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "对违法票据承兑、付款、保证罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 130 },
  { id: "criminal-l3-3-4-131", level: 3, label: "逃汇罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "逃汇罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 131 },
  { id: "criminal-l3-3-4-132", level: 3, label: "洗钱罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "洗钱罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 132 },
  { id: "criminal-l3-3-4-133", level: 3, label: "骗购外汇罪", parentId: "criminal-l2-3-4", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "破坏金融管理秩序罪", "骗购外汇罪"], chapterIndex: 3, sectionIndex: 4, itemIndex: 133 },
  { id: "criminal-l2-3-5", level: 2, label: "金融诈骗罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪"], chapterIndex: 3, sectionIndex: 5 },
  { id: "criminal-l3-3-5-134", level: 3, label: "集资诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "集资诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 134 },
  { id: "criminal-l3-3-5-135", level: 3, label: "贷款诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "贷款诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 135 },
  { id: "criminal-l3-3-5-136", level: 3, label: "票据诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "票据诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 136 },
  { id: "criminal-l3-3-5-137", level: 3, label: "金融凭证诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "金融凭证诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 137 },
  { id: "criminal-l3-3-5-138", level: 3, label: "信用证诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "信用证诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 138 },
  { id: "criminal-l3-3-5-139", level: 3, label: "信用卡诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "信用卡诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 139 },
  { id: "criminal-l3-3-5-140", level: 3, label: "有价证券诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "有价证券诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 140 },
  { id: "criminal-l3-3-5-141", level: 3, label: "保险诈骗罪", parentId: "criminal-l2-3-5", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "金融诈骗罪", "保险诈骗罪"], chapterIndex: 3, sectionIndex: 5, itemIndex: 141 },
  { id: "criminal-l2-3-6", level: 2, label: "危害税收征管罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪"], chapterIndex: 3, sectionIndex: 6 },
  { id: "criminal-l3-3-6-142", level: 3, label: "逃税罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "逃税罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 142 },
  { id: "criminal-l3-3-6-143", level: 3, label: "抗税罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "抗税罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 143 },
  { id: "criminal-l3-3-6-144", level: 3, label: "逃避追缴欠税罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "逃避追缴欠税罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 144 },
  { id: "criminal-l3-3-6-145", level: 3, label: "骗取出口退税罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "骗取出口退税罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 145 },
  { id: "criminal-l3-3-6-146", level: 3, label: "虚开增值税专用发票、用于骗取出口退税、抵扣税款发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "虚开增值税专用发票、用于骗取出口退税、抵扣税款发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 146 },
  { id: "criminal-l3-3-6-147", level: 3, label: "虚开发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "虚开发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 147 },
  { id: "criminal-l3-3-6-148", level: 3, label: "伪造、出售伪造的增值税专用发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "伪造、出售伪造的增值税专用发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 148 },
  { id: "criminal-l3-3-6-149", level: 3, label: "非法出售增值税专用发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "非法出售增值税专用发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 149 },
  { id: "criminal-l3-3-6-150", level: 3, label: "非法购买增值税专用发票、购买伪造的增值税专用发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "非法购买增值税专用发票、购买伪造的增值税专用发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 150 },
  { id: "criminal-l3-3-6-151", level: 3, label: "非法制造、出售非法制造的用于骗取出口退税、抵扣税款发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "非法制造、出售非法制造的用于骗取出口退税、抵扣税款发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 151 },
  { id: "criminal-l3-3-6-152", level: 3, label: "非法制造、出售非法制造的发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "非法制造、出售非法制造的发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 152 },
  { id: "criminal-l3-3-6-153", level: 3, label: "非法出售用于骗取出口退税、抵扣税款发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "非法出售用于骗取出口退税、抵扣税款发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 153 },
  { id: "criminal-l3-3-6-154", level: 3, label: "非法出售发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "非法出售发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 154 },
  { id: "criminal-l3-3-6-155", level: 3, label: "持有伪造的发票罪", parentId: "criminal-l2-3-6", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "危害税收征管罪", "持有伪造的发票罪"], chapterIndex: 3, sectionIndex: 6, itemIndex: 155 },
  { id: "criminal-l2-3-7", level: 2, label: "侵犯知识产权罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪"], chapterIndex: 3, sectionIndex: 7 },
  { id: "criminal-l3-3-7-156", level: 3, label: "假冒注册商标罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "假冒注册商标罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 156 },
  { id: "criminal-l3-3-7-157", level: 3, label: "销售假冒注册商标的商品罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "销售假冒注册商标的商品罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 157 },
  { id: "criminal-l3-3-7-158", level: 3, label: "非法制造、销售非法制造的注册商标标识罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "非法制造、销售非法制造的注册商标标识罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 158 },
  { id: "criminal-l3-3-7-159", level: 3, label: "假冒专利罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "假冒专利罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 159 },
  { id: "criminal-l3-3-7-160", level: 3, label: "侵犯著作权罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "侵犯著作权罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 160 },
  { id: "criminal-l3-3-7-161", level: 3, label: "销售侵权复制品罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "销售侵权复制品罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 161 },
  { id: "criminal-l3-3-7-162", level: 3, label: "侵犯商业秘密罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "侵犯商业秘密罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 162 },
  { id: "criminal-l3-3-7-163", level: 3, label: "为境外窃取、刺探、收买、非法提供商业秘密罪", parentId: "criminal-l2-3-7", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "侵犯知识产权罪", "为境外窃取、刺探、收买、非法提供商业秘密罪"], chapterIndex: 3, sectionIndex: 7, itemIndex: 163 },
  { id: "criminal-l2-3-8", level: 2, label: "扰乱市场秩序罪", parentId: "criminal-l1-3", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪"], chapterIndex: 3, sectionIndex: 8 },
  { id: "criminal-l3-3-8-164", level: 3, label: "损害商业信誉、商品声誉罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "损害商业信誉、商品声誉罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 164 },
  { id: "criminal-l3-3-8-165", level: 3, label: "虚假广告罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "虚假广告罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 165 },
  { id: "criminal-l3-3-8-166", level: 3, label: "串通投标罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "串通投标罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 166 },
  { id: "criminal-l3-3-8-167", level: 3, label: "合同诈骗罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "合同诈骗罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 167 },
  { id: "criminal-l3-3-8-168", level: 3, label: "组织、领导传销活动罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "组织、领导传销活动罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 168 },
  { id: "criminal-l3-3-8-169", level: 3, label: "非法经营罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "非法经营罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 169 },
  { id: "criminal-l3-3-8-170", level: 3, label: "强迫交易罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "强迫交易罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 170 },
  { id: "criminal-l3-3-8-171", level: 3, label: "伪造、倒卖伪造的有价票证罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "伪造、倒卖伪造的有价票证罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 171 },
  { id: "criminal-l3-3-8-172", level: 3, label: "倒卖车票、船票罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "倒卖车票、船票罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 172 },
  { id: "criminal-l3-3-8-173", level: 3, label: "非法转让、倒卖土地使用权罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "非法转让、倒卖土地使用权罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 173 },
  { id: "criminal-l3-3-8-174", level: 3, label: "提供虚假证明文件罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "提供虚假证明文件罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 174 },
  { id: "criminal-l3-3-8-175", level: 3, label: "出具证明文件重大失实罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "出具证明文件重大失实罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 175 },
  { id: "criminal-l3-3-8-176", level: 3, label: "逃避商检罪", parentId: "criminal-l2-3-8", path: ["刑事案由", "破坏社会主义市场经济秩序罪", "扰乱市场秩序罪", "逃避商检罪"], chapterIndex: 3, sectionIndex: 8, itemIndex: 176 },
  { id: "criminal-l1-4", level: 1, label: "侵犯公民人身权利、民主权利罪", parentId: null, path: ["刑事案由", "侵犯公民人身权利、民主权利罪"], chapterIndex: 4 },
  { id: "criminal-l3-4-0-177", level: 3, label: "故意杀人罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "故意杀人罪"], chapterIndex: 4, itemIndex: 177 },
  { id: "criminal-l3-4-0-178", level: 3, label: "过失致人死亡罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "过失致人死亡罪"], chapterIndex: 4, itemIndex: 178 },
  { id: "criminal-l3-4-0-179", level: 3, label: "故意伤害罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "故意伤害罪"], chapterIndex: 4, itemIndex: 179 },
  { id: "criminal-l3-4-0-180", level: 3, label: "组织出卖人体器官罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "组织出卖人体器官罪"], chapterIndex: 4, itemIndex: 180 },
  { id: "criminal-l3-4-0-181", level: 3, label: "过失致人重伤罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "过失致人重伤罪"], chapterIndex: 4, itemIndex: 181 },
  { id: "criminal-l3-4-0-182", level: 3, label: "强奸罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "强奸罪"], chapterIndex: 4, itemIndex: 182 },
  { id: "criminal-l3-4-0-183", level: 3, label: "负有照护职责人员性侵罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "负有照护职责人员性侵罪"], chapterIndex: 4, itemIndex: 183 },
  { id: "criminal-l3-4-0-184", level: 3, label: "强制猥亵、侮辱罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "强制猥亵、侮辱罪"], chapterIndex: 4, itemIndex: 184 },
  { id: "criminal-l3-4-0-185", level: 3, label: "猥亵儿童罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "猥亵儿童罪"], chapterIndex: 4, itemIndex: 185 },
  { id: "criminal-l3-4-0-186", level: 3, label: "非法拘禁罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "非法拘禁罪"], chapterIndex: 4, itemIndex: 186 },
  { id: "criminal-l3-4-0-187", level: 3, label: "绑架罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "绑架罪"], chapterIndex: 4, itemIndex: 187 },
  { id: "criminal-l3-4-0-188", level: 3, label: "拐卖妇女、儿童罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "拐卖妇女、儿童罪"], chapterIndex: 4, itemIndex: 188 },
  { id: "criminal-l3-4-0-189", level: 3, label: "收买被拐卖的妇女、儿童罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "收买被拐卖的妇女、儿童罪"], chapterIndex: 4, itemIndex: 189 },
  { id: "criminal-l3-4-0-190", level: 3, label: "聚众阻碍解救被收买的妇女、儿童罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "聚众阻碍解救被收买的妇女、儿童罪"], chapterIndex: 4, itemIndex: 190 },
  { id: "criminal-l3-4-0-191", level: 3, label: "诬告陷害罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "诬告陷害罪"], chapterIndex: 4, itemIndex: 191 },
  { id: "criminal-l3-4-0-192", level: 3, label: "强迫劳动罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "强迫劳动罪"], chapterIndex: 4, itemIndex: 192 },
  { id: "criminal-l3-4-0-193", level: 3, label: "雇用童工从事危重劳动罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "雇用童工从事危重劳动罪"], chapterIndex: 4, itemIndex: 193 },
  { id: "criminal-l3-4-0-194", level: 3, label: "非法搜查罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "非法搜查罪"], chapterIndex: 4, itemIndex: 194 },
  { id: "criminal-l3-4-0-195", level: 3, label: "非法侵入住宅罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "非法侵入住宅罪"], chapterIndex: 4, itemIndex: 195 },
  { id: "criminal-l3-4-0-196", level: 3, label: "侮辱罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "侮辱罪"], chapterIndex: 4, itemIndex: 196 },
  { id: "criminal-l3-4-0-197", level: 3, label: "诽谤罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "诽谤罪"], chapterIndex: 4, itemIndex: 197 },
  { id: "criminal-l3-4-0-198", level: 3, label: "刑讯逼供罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "刑讯逼供罪"], chapterIndex: 4, itemIndex: 198 },
  { id: "criminal-l3-4-0-199", level: 3, label: "暴力取证罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "暴力取证罪"], chapterIndex: 4, itemIndex: 199 },
  { id: "criminal-l3-4-0-200", level: 3, label: "虐待被监管人罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "虐待被监管人罪"], chapterIndex: 4, itemIndex: 200 },
  { id: "criminal-l3-4-0-201", level: 3, label: "煽动民族仇恨、民族歧视罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "煽动民族仇恨、民族歧视罪"], chapterIndex: 4, itemIndex: 201 },
  { id: "criminal-l3-4-0-202", level: 3, label: "出版歧视、侮辱少数民族作品罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "出版歧视、侮辱少数民族作品罪"], chapterIndex: 4, itemIndex: 202 },
  { id: "criminal-l3-4-0-203", level: 3, label: "非法剥夺公民宗教信仰自由罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "非法剥夺公民宗教信仰自由罪"], chapterIndex: 4, itemIndex: 203 },
  { id: "criminal-l3-4-0-204", level: 3, label: "侵犯少数民族风俗习惯罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "侵犯少数民族风俗习惯罪"], chapterIndex: 4, itemIndex: 204 },
  { id: "criminal-l3-4-0-205", level: 3, label: "侵犯通信自由罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "侵犯通信自由罪"], chapterIndex: 4, itemIndex: 205 },
  { id: "criminal-l3-4-0-206", level: 3, label: "私自开拆、隐匿、毁弃邮件、电报罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "私自开拆、隐匿、毁弃邮件、电报罪"], chapterIndex: 4, itemIndex: 206 },
  { id: "criminal-l3-4-0-207", level: 3, label: "侵犯公民个人信息罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "侵犯公民个人信息罪"], chapterIndex: 4, itemIndex: 207 },
  { id: "criminal-l3-4-0-208", level: 3, label: "报复陷害罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "报复陷害罪"], chapterIndex: 4, itemIndex: 208 },
  { id: "criminal-l3-4-0-209", level: 3, label: "打击报复会计、统计人员罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "打击报复会计、统计人员罪"], chapterIndex: 4, itemIndex: 209 },
  { id: "criminal-l3-4-0-210", level: 3, label: "破坏选举罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "破坏选举罪"], chapterIndex: 4, itemIndex: 210 },
  { id: "criminal-l3-4-0-211", level: 3, label: "暴力干涉婚姻自由罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "暴力干涉婚姻自由罪"], chapterIndex: 4, itemIndex: 211 },
  { id: "criminal-l3-4-0-212", level: 3, label: "重婚罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "重婚罪"], chapterIndex: 4, itemIndex: 212 },
  { id: "criminal-l3-4-0-213", level: 3, label: "破坏军婚罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "破坏军婚罪"], chapterIndex: 4, itemIndex: 213 },
  { id: "criminal-l3-4-0-214", level: 3, label: "虐待罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "虐待罪"], chapterIndex: 4, itemIndex: 214 },
  { id: "criminal-l3-4-0-215", level: 3, label: "虐待被监护、看护人罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "虐待被监护、看护人罪"], chapterIndex: 4, itemIndex: 215 },
  { id: "criminal-l3-4-0-216", level: 3, label: "遗弃罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "遗弃罪"], chapterIndex: 4, itemIndex: 216 },
  { id: "criminal-l3-4-0-217", level: 3, label: "拐骗儿童罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "拐骗儿童罪"], chapterIndex: 4, itemIndex: 217 },
  { id: "criminal-l3-4-0-218", level: 3, label: "组织残疾人、儿童乞讨罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "组织残疾人、儿童乞讨罪"], chapterIndex: 4, itemIndex: 218 },
  { id: "criminal-l3-4-0-219", level: 3, label: "组织未成年人进行违反治安管理活动罪", parentId: "criminal-l1-4", path: ["刑事案由", "侵犯公民人身权利、民主权利罪", "组织未成年人进行违反治安管理活动罪"], chapterIndex: 4, itemIndex: 219 },
  { id: "criminal-l1-5", level: 1, label: "侵犯财产罪", parentId: null, path: ["刑事案由", "侵犯财产罪"], chapterIndex: 5 },
  { id: "criminal-l3-5-0-220", level: 3, label: "抢劫罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "抢劫罪"], chapterIndex: 5, itemIndex: 220 },
  { id: "criminal-l3-5-0-221", level: 3, label: "盗窃罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "盗窃罪"], chapterIndex: 5, itemIndex: 221 },
  { id: "criminal-l3-5-0-222", level: 3, label: "诈骗罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "诈骗罪"], chapterIndex: 5, itemIndex: 222 },
  { id: "criminal-l3-5-0-223", level: 3, label: "抢夺罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "抢夺罪"], chapterIndex: 5, itemIndex: 223 },
  { id: "criminal-l3-5-0-224", level: 3, label: "聚众哄抢罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "聚众哄抢罪"], chapterIndex: 5, itemIndex: 224 },
  { id: "criminal-l3-5-0-225", level: 3, label: "侵占罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "侵占罪"], chapterIndex: 5, itemIndex: 225 },
  { id: "criminal-l3-5-0-226", level: 3, label: "职务侵占罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "职务侵占罪"], chapterIndex: 5, itemIndex: 226 },
  { id: "criminal-l3-5-0-227", level: 3, label: "挪用资金罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "挪用资金罪"], chapterIndex: 5, itemIndex: 227 },
  { id: "criminal-l3-5-0-228", level: 3, label: "挪用特定款物罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "挪用特定款物罪"], chapterIndex: 5, itemIndex: 228 },
  { id: "criminal-l3-5-0-229", level: 3, label: "敲诈勒索罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "敲诈勒索罪"], chapterIndex: 5, itemIndex: 229 },
  { id: "criminal-l3-5-0-230", level: 3, label: "故意毁坏财物罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "故意毁坏财物罪"], chapterIndex: 5, itemIndex: 230 },
  { id: "criminal-l3-5-0-231", level: 3, label: "破坏生产经营罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "破坏生产经营罪"], chapterIndex: 5, itemIndex: 231 },
  { id: "criminal-l3-5-0-232", level: 3, label: "拒不支付劳动报酬罪", parentId: "criminal-l1-5", path: ["刑事案由", "侵犯财产罪", "拒不支付劳动报酬罪"], chapterIndex: 5, itemIndex: 232 },
  { id: "criminal-l1-6", level: 1, label: "妨害社会管理秩序罪", parentId: null, path: ["刑事案由", "妨害社会管理秩序罪"], chapterIndex: 6 },
  { id: "criminal-l2-6-1", level: 2, label: "扰乱公共秩序罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪"], chapterIndex: 6, sectionIndex: 1 },
  { id: "criminal-l3-6-1-233", level: 3, label: "妨害公务罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "妨害公务罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 233 },
  { id: "criminal-l3-6-1-234", level: 3, label: "袭警罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "袭警罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 234 },
  { id: "criminal-l3-6-1-235", level: 3, label: "煽动暴力抗拒法律实施罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "煽动暴力抗拒法律实施罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 235 },
  { id: "criminal-l3-6-1-236", level: 3, label: "招摇撞骗罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "招摇撞骗罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 236 },
  { id: "criminal-l3-6-1-237", level: 3, label: "伪造、变造、买卖国家机关公文、证件、印章罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "伪造、变造、买卖国家机关公文、证件、印章罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 237 },
  { id: "criminal-l3-6-1-238", level: 3, label: "盗窃、抢夺、毁灭国家机关公文、证件、印章罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "盗窃、抢夺、毁灭国家机关公文、证件、印章罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 238 },
  { id: "criminal-l3-6-1-239", level: 3, label: "伪造公司、企业、事业单位、人民团体印章罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "伪造公司、企业、事业单位、人民团体印章罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 239 },
  { id: "criminal-l3-6-1-240", level: 3, label: "伪造、变造、买卖身份证件罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "伪造、变造、买卖身份证件罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 240 },
  { id: "criminal-l3-6-1-241", level: 3, label: "使用虚假身份证件、盗用身份证件罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "使用虚假身份证件、盗用身份证件罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 241 },
  { id: "criminal-l3-6-1-242", level: 3, label: "冒名顶替罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "冒名顶替罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 242 },
  { id: "criminal-l3-6-1-243", level: 3, label: "非法生产、买卖警用装备罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法生产、买卖警用装备罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 243 },
  { id: "criminal-l3-6-1-244", level: 3, label: "非法获取国家秘密罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法获取国家秘密罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 244 },
  { id: "criminal-l3-6-1-245", level: 3, label: "非法持有国家绝密、机密文件、资料、物品罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法持有国家绝密、机密文件、资料、物品罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 245 },
  { id: "criminal-l3-6-1-246", level: 3, label: "非法生产、销售专用间谍器材、窃听、窃照专用器材罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法生产、销售专用间谍器材、窃听、窃照专用器材罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 246 },
  { id: "criminal-l3-6-1-247", level: 3, label: "非法使用窃听、窃照专用器材罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法使用窃听、窃照专用器材罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 247 },
  { id: "criminal-l3-6-1-248", level: 3, label: "组织考试作弊罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "组织考试作弊罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 248 },
  { id: "criminal-l3-6-1-249", level: 3, label: "非法出售、提供试题、答案罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法出售、提供试题、答案罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 249 },
  { id: "criminal-l3-6-1-250", level: 3, label: "代替考试罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "代替考试罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 250 },
  { id: "criminal-l3-6-1-251", level: 3, label: "非法侵入计算机信息系统罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法侵入计算机信息系统罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 251 },
  { id: "criminal-l3-6-1-252", level: 3, label: "非法获取计算机信息系统数据、非法控制计算机信息系统罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法获取计算机信息系统数据、非法控制计算机信息系统罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 252 },
  { id: "criminal-l3-6-1-253", level: 3, label: "提供侵入、非法控制计算机信息系统程序、工具罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "提供侵入、非法控制计算机信息系统程序、工具罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 253 },
  { id: "criminal-l3-6-1-254", level: 3, label: "破坏计算机信息系统罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "破坏计算机信息系统罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 254 },
  { id: "criminal-l3-6-1-255", level: 3, label: "拒不履行信息网络安全管理义务罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "拒不履行信息网络安全管理义务罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 255 },
  { id: "criminal-l3-6-1-256", level: 3, label: "非法利用信息网络罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法利用信息网络罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 256 },
  { id: "criminal-l3-6-1-257", level: 3, label: "帮助信息网络犯罪活动罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "帮助信息网络犯罪活动罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 257 },
  { id: "criminal-l3-6-1-258", level: 3, label: "扰乱无线电通讯管理秩序罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "扰乱无线电通讯管理秩序罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 258 },
  { id: "criminal-l3-6-1-259", level: 3, label: "聚众扰乱社会秩序罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "聚众扰乱社会秩序罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 259 },
  { id: "criminal-l3-6-1-260", level: 3, label: "聚众冲击国家机关罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "聚众冲击国家机关罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 260 },
  { id: "criminal-l3-6-1-261", level: 3, label: "扰乱国家机关工作秩序罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "扰乱国家机关工作秩序罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 261 },
  { id: "criminal-l3-6-1-262", level: 3, label: "组织、资助非法聚集罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "组织、资助非法聚集罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 262 },
  { id: "criminal-l3-6-1-263", level: 3, label: "聚众扰乱公共场所秩序、交通秩序罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "聚众扰乱公共场所秩序、交通秩序罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 263 },
  { id: "criminal-l3-6-1-264", level: 3, label: "投放虚假危险物质罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "投放虚假危险物质罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 264 },
  { id: "criminal-l3-6-1-265", level: 3, label: "编造、故意传播虚假恐怖信息罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "编造、故意传播虚假恐怖信息罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 265 },
  { id: "criminal-l3-6-1-266", level: 3, label: "编造、故意传播虚假信息罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "编造、故意传播虚假信息罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 266 },
  { id: "criminal-l3-6-1-267", level: 3, label: "高空抛物罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "高空抛物罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 267 },
  { id: "criminal-l3-6-1-268", level: 3, label: "聚众斗殴罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "聚众斗殴罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 268 },
  { id: "criminal-l3-6-1-269", level: 3, label: "寻衅滋事罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "寻衅滋事罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 269 },
  { id: "criminal-l3-6-1-270", level: 3, label: "催收非法债务罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "催收非法债务罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 270 },
  { id: "criminal-l3-6-1-271", level: 3, label: "组织、领导、参加黑社会性质组织罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "组织、领导、参加黑社会性质组织罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 271 },
  { id: "criminal-l3-6-1-272", level: 3, label: "入境发展黑社会组织罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "入境发展黑社会组织罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 272 },
  { id: "criminal-l3-6-1-273", level: 3, label: "包庇、纵容黑社会性质组织罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "包庇、纵容黑社会性质组织罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 273 },
  { id: "criminal-l3-6-1-274", level: 3, label: "传授犯罪方法罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "传授犯罪方法罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 274 },
  { id: "criminal-l3-6-1-275", level: 3, label: "非法集会、游行、示威罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法集会、游行、示威罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 275 },
  { id: "criminal-l3-6-1-276", level: 3, label: "非法携带武器、管制刀具、爆炸物参加集会、游行、示威罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "非法携带武器、管制刀具、爆炸物参加集会、游行、示威罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 276 },
  { id: "criminal-l3-6-1-277", level: 3, label: "破坏集会、游行、示威罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "破坏集会、游行、示威罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 277 },
  { id: "criminal-l3-6-1-278", level: 3, label: "侮辱国旗、国徽、国歌罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "侮辱国旗、国徽、国歌罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 278 },
  { id: "criminal-l3-6-1-279", level: 3, label: "侵害英雄烈士名誉、荣誉罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "侵害英雄烈士名誉、荣誉罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 279 },
  { id: "criminal-l3-6-1-280", level: 3, label: "组织、利用会道门、邪教组织、利用迷信破坏法律实施罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "组织、利用会道门、邪教组织、利用迷信破坏法律实施罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 280 },
  { id: "criminal-l3-6-1-281", level: 3, label: "组织、利用会道门、邪教组织、利用迷信致人重伤、死亡罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "组织、利用会道门、邪教组织、利用迷信致人重伤、死亡罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 281 },
  { id: "criminal-l3-6-1-282", level: 3, label: "聚众淫乱罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "聚众淫乱罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 282 },
  { id: "criminal-l3-6-1-283", level: 3, label: "引诱未成年人聚众淫乱罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "引诱未成年人聚众淫乱罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 283 },
  { id: "criminal-l3-6-1-284", level: 3, label: "盗窃、侮辱、故意毁坏尸体、尸骨、骨灰罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "盗窃、侮辱、故意毁坏尸体、尸骨、骨灰罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 284 },
  { id: "criminal-l3-6-1-285", level: 3, label: "赌博罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "赌博罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 285 },
  { id: "criminal-l3-6-1-286", level: 3, label: "开设赌场罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "开设赌场罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 286 },
  { id: "criminal-l3-6-1-287", level: 3, label: "组织参与国（境）外赌博罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "组织参与国（境）外赌博罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 287 },
  { id: "criminal-l3-6-1-288", level: 3, label: "故意延误投递邮件罪", parentId: "criminal-l2-6-1", path: ["刑事案由", "妨害社会管理秩序罪", "扰乱公共秩序罪", "故意延误投递邮件罪"], chapterIndex: 6, sectionIndex: 1, itemIndex: 288 },
  { id: "criminal-l2-6-2", level: 2, label: "妨害司法罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪"], chapterIndex: 6, sectionIndex: 2 },
  { id: "criminal-l3-6-2-289", level: 3, label: "伪证罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "伪证罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 289 },
  { id: "criminal-l3-6-2-290", level: 3, label: "辩护人、诉讼代理人毁灭证据、伪造证据、妨害作证罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "辩护人、诉讼代理人毁灭证据、伪造证据、妨害作证罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 290 },
  { id: "criminal-l3-6-2-291", level: 3, label: "妨害作证罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "妨害作证罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 291 },
  { id: "criminal-l3-6-2-292", level: 3, label: "帮助毁灭、伪造证据罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "帮助毁灭、伪造证据罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 292 },
  { id: "criminal-l3-6-2-293", level: 3, label: "虚假诉讼罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "虚假诉讼罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 293 },
  { id: "criminal-l3-6-2-294", level: 3, label: "打击报复证人罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "打击报复证人罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 294 },
  { id: "criminal-l3-6-2-295", level: 3, label: "泄露不应公开的案件信息罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "泄露不应公开的案件信息罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 295 },
  { id: "criminal-l3-6-2-296", level: 3, label: "披露、报道不应公开的案件信息罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "披露、报道不应公开的案件信息罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 296 },
  { id: "criminal-l3-6-2-297", level: 3, label: "扰乱法庭秩序罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "扰乱法庭秩序罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 297 },
  { id: "criminal-l3-6-2-298", level: 3, label: "窝藏、包庇罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "窝藏、包庇罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 298 },
  { id: "criminal-l3-6-2-299", level: 3, label: "拒绝提供间谍犯罪、恐怖主义犯罪、极端主义犯罪证据罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "拒绝提供间谍犯罪、恐怖主义犯罪、极端主义犯罪证据罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 299 },
  { id: "criminal-l3-6-2-300", level: 3, label: "掩饰、隐瞒犯罪所得、犯罪所得收益罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "掩饰、隐瞒犯罪所得、犯罪所得收益罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 300 },
  { id: "criminal-l3-6-2-301", level: 3, label: "拒不执行判决、裁定罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "拒不执行判决、裁定罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 301 },
  { id: "criminal-l3-6-2-302", level: 3, label: "非法处置查封、扣押、冻结的财产罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "非法处置查封、扣押、冻结的财产罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 302 },
  { id: "criminal-l3-6-2-303", level: 3, label: "破坏监管秩序罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "破坏监管秩序罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 303 },
  { id: "criminal-l3-6-2-304", level: 3, label: "脱逃罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "脱逃罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 304 },
  { id: "criminal-l3-6-2-305", level: 3, label: "劫夺被押解人员罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "劫夺被押解人员罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 305 },
  { id: "criminal-l3-6-2-306", level: 3, label: "组织越狱罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "组织越狱罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 306 },
  { id: "criminal-l3-6-2-307", level: 3, label: "暴动越狱罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "暴动越狱罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 307 },
  { id: "criminal-l3-6-2-308", level: 3, label: "聚众持械劫狱罪", parentId: "criminal-l2-6-2", path: ["刑事案由", "妨害社会管理秩序罪", "妨害司法罪", "聚众持械劫狱罪"], chapterIndex: 6, sectionIndex: 2, itemIndex: 308 },
  { id: "criminal-l2-6-3", level: 2, label: "妨害国（边）境管理罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪"], chapterIndex: 6, sectionIndex: 3 },
  { id: "criminal-l3-6-3-309", level: 3, label: "组织他人偷越国（边）境罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "组织他人偷越国（边）境罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 309 },
  { id: "criminal-l3-6-3-310", level: 3, label: "骗取出境证件罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "骗取出境证件罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 310 },
  { id: "criminal-l3-6-3-311", level: 3, label: "提供伪造、变造的出入境证件罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "提供伪造、变造的出入境证件罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 311 },
  { id: "criminal-l3-6-3-312", level: 3, label: "出售出入境证件罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "出售出入境证件罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 312 },
  { id: "criminal-l3-6-3-313", level: 3, label: "运送他人偷越国（边）境罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "运送他人偷越国（边）境罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 313 },
  { id: "criminal-l3-6-3-314", level: 3, label: "偷越国（边）境罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "偷越国（边）境罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 314 },
  { id: "criminal-l3-6-3-315", level: 3, label: "破坏界碑、界桩罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "破坏界碑、界桩罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 315 },
  { id: "criminal-l3-6-3-316", level: 3, label: "破坏永久性测量标志罪", parentId: "criminal-l2-6-3", path: ["刑事案由", "妨害社会管理秩序罪", "妨害国（边）境管理罪", "破坏永久性测量标志罪"], chapterIndex: 6, sectionIndex: 3, itemIndex: 316 },
  { id: "criminal-l2-6-4", level: 2, label: "妨害文物管理罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪"], chapterIndex: 6, sectionIndex: 4 },
  { id: "criminal-l3-6-4-317", level: 3, label: "故意损毁文物罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "故意损毁文物罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 317 },
  { id: "criminal-l3-6-4-318", level: 3, label: "故意损毁名胜古迹罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "故意损毁名胜古迹罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 318 },
  { id: "criminal-l3-6-4-319", level: 3, label: "过失损毁文物罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "过失损毁文物罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 319 },
  { id: "criminal-l3-6-4-320", level: 3, label: "非法向外国人出售、赠送珍贵文物罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "非法向外国人出售、赠送珍贵文物罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 320 },
  { id: "criminal-l3-6-4-321", level: 3, label: "倒卖文物罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "倒卖文物罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 321 },
  { id: "criminal-l3-6-4-322", level: 3, label: "非法出售、私赠文物藏品罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "非法出售、私赠文物藏品罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 322 },
  { id: "criminal-l3-6-4-323", level: 3, label: "盗掘古文化遗址、古墓葬罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "盗掘古文化遗址、古墓葬罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 323 },
  { id: "criminal-l3-6-4-324", level: 3, label: "盗掘古人类化石、古脊椎动物化石罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "盗掘古人类化石、古脊椎动物化石罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 324 },
  { id: "criminal-l3-6-4-325", level: 3, label: "抢夺、窃取国有档案罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "抢夺、窃取国有档案罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 325 },
  { id: "criminal-l3-6-4-326", level: 3, label: "擅自出卖、转让国有档案罪", parentId: "criminal-l2-6-4", path: ["刑事案由", "妨害社会管理秩序罪", "妨害文物管理罪", "擅自出卖、转让国有档案罪"], chapterIndex: 6, sectionIndex: 4, itemIndex: 326 },
  { id: "criminal-l2-6-5", level: 2, label: "危害公共卫生罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪"], chapterIndex: 6, sectionIndex: 5 },
  { id: "criminal-l3-6-5-327", level: 3, label: "妨害传染病防治罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "妨害传染病防治罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 327 },
  { id: "criminal-l3-6-5-328", level: 3, label: "传染病菌种、毒种扩散罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "传染病菌种、毒种扩散罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 328 },
  { id: "criminal-l3-6-5-329", level: 3, label: "妨害国境卫生检疫罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "妨害国境卫生检疫罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 329 },
  { id: "criminal-l3-6-5-330", level: 3, label: "非法组织卖血罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "非法组织卖血罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 330 },
  { id: "criminal-l3-6-5-331", level: 3, label: "强迫卖血罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "强迫卖血罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 331 },
  { id: "criminal-l3-6-5-332", level: 3, label: "非法采集、供应血液、制作、供应血液制品罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "非法采集、供应血液、制作、供应血液制品罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 332 },
  { id: "criminal-l3-6-5-333", level: 3, label: "采集、供应血液、制作、供应血液制品事故罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "采集、供应血液、制作、供应血液制品事故罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 333 },
  { id: "criminal-l3-6-5-334", level: 3, label: "非法采集人类遗传资源、走私人类遗传资源材料罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "非法采集人类遗传资源、走私人类遗传资源材料罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 334 },
  { id: "criminal-l3-6-5-335", level: 3, label: "医疗事故罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "医疗事故罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 335 },
  { id: "criminal-l3-6-5-336", level: 3, label: "非法行医罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "非法行医罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 336 },
  { id: "criminal-l3-6-5-337", level: 3, label: "非法进行节育手术罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "非法进行节育手术罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 337 },
  { id: "criminal-l3-6-5-338", level: 3, label: "非法植入基因编辑、克隆胚胎罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "非法植入基因编辑、克隆胚胎罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 338 },
  { id: "criminal-l3-6-5-339", level: 3, label: "妨害动植物防疫、检疫罪", parentId: "criminal-l2-6-5", path: ["刑事案由", "妨害社会管理秩序罪", "危害公共卫生罪", "妨害动植物防疫、检疫罪"], chapterIndex: 6, sectionIndex: 5, itemIndex: 339 },
  { id: "criminal-l2-6-6", level: 2, label: "破坏环境资源保护罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪"], chapterIndex: 6, sectionIndex: 6 },
  { id: "criminal-l3-6-6-340", level: 3, label: "污染环境罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "污染环境罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 340 },
  { id: "criminal-l3-6-6-341", level: 3, label: "非法处置进口的固体废物罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法处置进口的固体废物罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 341 },
  { id: "criminal-l3-6-6-342", level: 3, label: "擅自进口固体废物罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "擅自进口固体废物罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 342 },
  { id: "criminal-l3-6-6-343", level: 3, label: "非法捕捞水产品罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法捕捞水产品罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 343 },
  { id: "criminal-l3-6-6-344", level: 3, label: "危害珍贵、濒危野生动物罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "危害珍贵、濒危野生动物罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 344 },
  { id: "criminal-l3-6-6-345", level: 3, label: "非法狩猎罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法狩猎罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 345 },
  { id: "criminal-l3-6-6-346", level: 3, label: "非法猎捕、收购、运输、出售陆生野生动物罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法猎捕、收购、运输、出售陆生野生动物罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 346 },
  { id: "criminal-l3-6-6-347", level: 3, label: "非法占用农用地罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法占用农用地罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 347 },
  { id: "criminal-l3-6-6-348", level: 3, label: "破坏自然保护地罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "破坏自然保护地罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 348 },
  { id: "criminal-l3-6-6-349", level: 3, label: "非法采矿罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法采矿罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 349 },
  { id: "criminal-l3-6-6-350", level: 3, label: "破坏性采矿罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "破坏性采矿罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 350 },
  { id: "criminal-l3-6-6-351", level: 3, label: "危害国家重点保护植物罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "危害国家重点保护植物罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 351 },
  { id: "criminal-l3-6-6-352", level: 3, label: "非法引进、释放、丢弃外来入侵物种罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法引进、释放、丢弃外来入侵物种罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 352 },
  { id: "criminal-l3-6-6-353", level: 3, label: "盗伐林木罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "盗伐林木罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 353 },
  { id: "criminal-l3-6-6-354", level: 3, label: "滥伐林木罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "滥伐林木罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 354 },
  { id: "criminal-l3-6-6-355", level: 3, label: "非法收购、运输盗伐、滥伐的林木罪", parentId: "criminal-l2-6-6", path: ["刑事案由", "妨害社会管理秩序罪", "破坏环境资源保护罪", "非法收购、运输盗伐、滥伐的林木罪"], chapterIndex: 6, sectionIndex: 6, itemIndex: 355 },
  { id: "criminal-l2-6-7", level: 2, label: "走私、贩卖、运输、制造毒 品罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪"], chapterIndex: 6, sectionIndex: 7 },
  { id: "criminal-l3-6-7-356", level: 3, label: "走私、贩卖、运输、制造毒 品罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "走私、贩卖、运输、制造毒 品罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 356 },
  { id: "criminal-l3-6-7-357", level: 3, label: "非法持有毒 品罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "非法持有毒 品罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 357 },
  { id: "criminal-l3-6-7-358", level: 3, label: "包庇毒 品犯罪分子罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "包庇毒 品犯罪分子罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 358 },
  { id: "criminal-l3-6-7-359", level: 3, label: "窝藏、转移、隐瞒毒 品、毒赃罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "窝藏、转移、隐瞒毒 品、毒赃罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 359 },
  { id: "criminal-l3-6-7-360", level: 3, label: "非法生产、买卖、运输制毒物品、走私制毒物品罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "非法生产、买卖、运输制毒物品、走私制毒物品罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 360 },
  { id: "criminal-l3-6-7-361", level: 3, label: "非法种植毒 品原植物罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "非法种植毒 品原植物罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 361 },
  { id: "criminal-l3-6-7-362", level: 3, label: "非法买卖、运输、携带、持有毒 品原植物种子、幼苗罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "非法买卖、运输、携带、持有毒 品原植物种子、幼苗罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 362 },
  { id: "criminal-l3-6-7-363", level: 3, label: "引诱、教唆、欺骗他人吸毒罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "引诱、教唆、欺骗他人吸毒罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 363 },
  { id: "criminal-l3-6-7-364", level: 3, label: "强迫他人吸毒罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "强迫他人吸毒罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 364 },
  { id: "criminal-l3-6-7-365", level: 3, label: "容留他人吸毒罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "容留他人吸毒罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 365 },
  { id: "criminal-l3-6-7-366", level: 3, label: "非法提供麻醉药品、精神药品罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "非法提供麻醉药品、精神药品罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 366 },
  { id: "criminal-l3-6-7-367", level: 3, label: "妨害兴奋剂管理罪", parentId: "criminal-l2-6-7", path: ["刑事案由", "妨害社会管理秩序罪", "走私、贩卖、运输、制造毒 品罪", "妨害兴奋剂管理罪"], chapterIndex: 6, sectionIndex: 7, itemIndex: 367 },
  { id: "criminal-l2-6-8", level: 2, label: "组织、强迫、引诱、容留、介绍卖淫罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪"], chapterIndex: 6, sectionIndex: 8 },
  { id: "criminal-l3-6-8-368", level: 3, label: "组织卖淫罪", parentId: "criminal-l2-6-8", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪", "组织卖淫罪"], chapterIndex: 6, sectionIndex: 8, itemIndex: 368 },
  { id: "criminal-l3-6-8-369", level: 3, label: "强迫卖淫罪", parentId: "criminal-l2-6-8", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪", "强迫卖淫罪"], chapterIndex: 6, sectionIndex: 8, itemIndex: 369 },
  { id: "criminal-l3-6-8-370", level: 3, label: "协助组织卖淫罪", parentId: "criminal-l2-6-8", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪", "协助组织卖淫罪"], chapterIndex: 6, sectionIndex: 8, itemIndex: 370 },
  { id: "criminal-l3-6-8-371", level: 3, label: "引诱、容留、介绍卖淫罪", parentId: "criminal-l2-6-8", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪", "引诱、容留、介绍卖淫罪"], chapterIndex: 6, sectionIndex: 8, itemIndex: 371 },
  { id: "criminal-l3-6-8-372", level: 3, label: "引诱幼女卖淫罪", parentId: "criminal-l2-6-8", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪", "引诱幼女卖淫罪"], chapterIndex: 6, sectionIndex: 8, itemIndex: 372 },
  { id: "criminal-l3-6-8-373", level: 3, label: "传播性病罪", parentId: "criminal-l2-6-8", path: ["刑事案由", "妨害社会管理秩序罪", "组织、强迫、引诱、容留、介绍卖淫罪", "传播性病罪"], chapterIndex: 6, sectionIndex: 8, itemIndex: 373 },
  { id: "criminal-l2-6-9", level: 2, label: "制作、贩卖、传播淫秽物品罪", parentId: "criminal-l1-6", path: ["刑事案由", "妨害社会管理秩序罪", "制作、贩卖、传播淫秽物品罪"], chapterIndex: 6, sectionIndex: 9 },
  { id: "criminal-l3-6-9-374", level: 3, label: "制作、复制、出版、贩卖、传播淫秽物品牟利罪", parentId: "criminal-l2-6-9", path: ["刑事案由", "妨害社会管理秩序罪", "制作、贩卖、传播淫秽物品罪", "制作、复制、出版、贩卖、传播淫秽物品牟利罪"], chapterIndex: 6, sectionIndex: 9, itemIndex: 374 },
  { id: "criminal-l3-6-9-375", level: 3, label: "为他人提供书号出版淫秽书刊罪", parentId: "criminal-l2-6-9", path: ["刑事案由", "妨害社会管理秩序罪", "制作、贩卖、传播淫秽物品罪", "为他人提供书号出版淫秽书刊罪"], chapterIndex: 6, sectionIndex: 9, itemIndex: 375 },
  { id: "criminal-l3-6-9-376", level: 3, label: "传播淫秽物品罪", parentId: "criminal-l2-6-9", path: ["刑事案由", "妨害社会管理秩序罪", "制作、贩卖、传播淫秽物品罪", "传播淫秽物品罪"], chapterIndex: 6, sectionIndex: 9, itemIndex: 376 },
  { id: "criminal-l3-6-9-377", level: 3, label: "组织播放淫秽音像制品罪", parentId: "criminal-l2-6-9", path: ["刑事案由", "妨害社会管理秩序罪", "制作、贩卖、传播淫秽物品罪", "组织播放淫秽音像制品罪"], chapterIndex: 6, sectionIndex: 9, itemIndex: 377 },
  { id: "criminal-l3-6-9-378", level: 3, label: "组织淫秽表演罪", parentId: "criminal-l2-6-9", path: ["刑事案由", "妨害社会管理秩序罪", "制作、贩卖、传播淫秽物品罪", "组织淫秽表演罪"], chapterIndex: 6, sectionIndex: 9, itemIndex: 378 },
  { id: "criminal-l1-7", level: 1, label: "危害国防利益罪", parentId: null, path: ["刑事案由", "危害国防利益罪"], chapterIndex: 7 },
  { id: "criminal-l3-7-0-379", level: 3, label: "阻碍军人执行职务罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "阻碍军人执行职务罪"], chapterIndex: 7, itemIndex: 379 },
  { id: "criminal-l3-7-0-380", level: 3, label: "阻碍军事行动罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "阻碍军事行动罪"], chapterIndex: 7, itemIndex: 380 },
  { id: "criminal-l3-7-0-381", level: 3, label: "破坏武器装备、军事设施、军事通信罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "破坏武器装备、军事设施、军事通信罪"], chapterIndex: 7, itemIndex: 381 },
  { id: "criminal-l3-7-0-382", level: 3, label: "过失损坏武器装备、军事设施、军事通信罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "过失损坏武器装备、军事设施、军事通信罪"], chapterIndex: 7, itemIndex: 382 },
  { id: "criminal-l3-7-0-383", level: 3, label: "故意提供不合格武器装备、军事设施罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "故意提供不合格武器装备、军事设施罪"], chapterIndex: 7, itemIndex: 383 },
  { id: "criminal-l3-7-0-384", level: 3, label: "过失提供不合格武器装备、军事设施罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "过失提供不合格武器装备、军事设施罪"], chapterIndex: 7, itemIndex: 384 },
  { id: "criminal-l3-7-0-385", level: 3, label: "聚众冲击军事禁区罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "聚众冲击军事禁区罪"], chapterIndex: 7, itemIndex: 385 },
  { id: "criminal-l3-7-0-386", level: 3, label: "聚众扰乱军事管理区秩序罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "聚众扰乱军事管理区秩序罪"], chapterIndex: 7, itemIndex: 386 },
  { id: "criminal-l3-7-0-387", level: 3, label: "冒充军人招摇撞骗罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "冒充军人招摇撞骗罪"], chapterIndex: 7, itemIndex: 387 },
  { id: "criminal-l3-7-0-388", level: 3, label: "煽动军人逃离部队罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "煽动军人逃离部队罪"], chapterIndex: 7, itemIndex: 388 },
  { id: "criminal-l3-7-0-389", level: 3, label: "雇用逃离部队军人罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "雇用逃离部队军人罪"], chapterIndex: 7, itemIndex: 389 },
  { id: "criminal-l3-7-0-390", level: 3, label: "接送不合格兵员罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "接送不合格兵员罪"], chapterIndex: 7, itemIndex: 390 },
  { id: "criminal-l3-7-0-391", level: 3, label: "伪造、变造、买卖武装部队公文、证件、印章罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "伪造、变造、买卖武装部队公文、证件、印章罪"], chapterIndex: 7, itemIndex: 391 },
  { id: "criminal-l3-7-0-392", level: 3, label: "盗窃、抢夺武装部队公文、证件、印章罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "盗窃、抢夺武装部队公文、证件、印章罪"], chapterIndex: 7, itemIndex: 392 },
  { id: "criminal-l3-7-0-393", level: 3, label: "非法生产、买卖武装部队制式服装罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "非法生产、买卖武装部队制式服装罪"], chapterIndex: 7, itemIndex: 393 },
  { id: "criminal-l3-7-0-394", level: 3, label: "伪造、盗窃、买卖、非法提供、非法使用武装部队专用标志罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "伪造、盗窃、买卖、非法提供、非法使用武装部队专用标志罪"], chapterIndex: 7, itemIndex: 394 },
  { id: "criminal-l3-7-0-395", level: 3, label: "战时拒绝、逃避征召、军事训练罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时拒绝、逃避征召、军事训练罪"], chapterIndex: 7, itemIndex: 395 },
  { id: "criminal-l3-7-0-396", level: 3, label: "战时拒绝、逃避服役罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时拒绝、逃避服役罪"], chapterIndex: 7, itemIndex: 396 },
  { id: "criminal-l3-7-0-397", level: 3, label: "战时故意提供虚假敌情罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时故意提供虚假敌情罪"], chapterIndex: 7, itemIndex: 397 },
  { id: "criminal-l3-7-0-398", level: 3, label: "战时造谣扰乱军心罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时造谣扰乱军心罪"], chapterIndex: 7, itemIndex: 398 },
  { id: "criminal-l3-7-0-399", level: 3, label: "战时窝藏逃离部队军人罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时窝藏逃离部队军人罪"], chapterIndex: 7, itemIndex: 399 },
  { id: "criminal-l3-7-0-400", level: 3, label: "战时拒绝、故意延误军事订货罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时拒绝、故意延误军事订货罪"], chapterIndex: 7, itemIndex: 400 },
  { id: "criminal-l3-7-0-401", level: 3, label: "战时拒绝军事征收、征用罪", parentId: "criminal-l1-7", path: ["刑事案由", "危害国防利益罪", "战时拒绝军事征收、征用罪"], chapterIndex: 7, itemIndex: 401 },
  { id: "criminal-l1-8", level: 1, label: "贪污贿赂罪", parentId: null, path: ["刑事案由", "贪污贿赂罪"], chapterIndex: 8 },
  { id: "criminal-l3-8-0-402", level: 3, label: "贪污罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "贪污罪"], chapterIndex: 8, itemIndex: 402 },
  { id: "criminal-l3-8-0-403", level: 3, label: "挪用公款罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "挪用公款罪"], chapterIndex: 8, itemIndex: 403 },
  { id: "criminal-l3-8-0-404", level: 3, label: "受贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "受贿罪"], chapterIndex: 8, itemIndex: 404 },
  { id: "criminal-l3-8-0-405", level: 3, label: "单位受贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "单位受贿罪"], chapterIndex: 8, itemIndex: 405 },
  { id: "criminal-l3-8-0-406", level: 3, label: "利用影响力受贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "利用影响力受贿罪"], chapterIndex: 8, itemIndex: 406 },
  { id: "criminal-l3-8-0-407", level: 3, label: "行贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "行贿罪"], chapterIndex: 8, itemIndex: 407 },
  { id: "criminal-l3-8-0-408", level: 3, label: "对有影响力的人行贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "对有影响力的人行贿罪"], chapterIndex: 8, itemIndex: 408 },
  { id: "criminal-l3-8-0-409", level: 3, label: "对单位行贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "对单位行贿罪"], chapterIndex: 8, itemIndex: 409 },
  { id: "criminal-l3-8-0-410", level: 3, label: "介绍贿赂罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "介绍贿赂罪"], chapterIndex: 8, itemIndex: 410 },
  { id: "criminal-l3-8-0-411", level: 3, label: "单位行贿罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "单位行贿罪"], chapterIndex: 8, itemIndex: 411 },
  { id: "criminal-l3-8-0-412", level: 3, label: "巨额财产来源不明罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "巨额财产来源不明罪"], chapterIndex: 8, itemIndex: 412 },
  { id: "criminal-l3-8-0-413", level: 3, label: "隐瞒境外存款罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "隐瞒境外存款罪"], chapterIndex: 8, itemIndex: 413 },
  { id: "criminal-l3-8-0-414", level: 3, label: "私分国有资产罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "私分国有资产罪"], chapterIndex: 8, itemIndex: 414 },
  { id: "criminal-l3-8-0-415", level: 3, label: "私分罚没财物罪", parentId: "criminal-l1-8", path: ["刑事案由", "贪污贿赂罪", "私分罚没财物罪"], chapterIndex: 8, itemIndex: 415 },
  { id: "criminal-l1-9", level: 1, label: "渎职罪", parentId: null, path: ["刑事案由", "渎职罪"], chapterIndex: 9 },
  { id: "criminal-l3-9-0-416", level: 3, label: "滥用职权罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "滥用职权罪"], chapterIndex: 9, itemIndex: 416 },
  { id: "criminal-l3-9-0-417", level: 3, label: "玩忽职守罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "玩忽职守罪"], chapterIndex: 9, itemIndex: 417 },
  { id: "criminal-l3-9-0-418", level: 3, label: "故意泄露国家秘密罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "故意泄露国家秘密罪"], chapterIndex: 9, itemIndex: 418 },
  { id: "criminal-l3-9-0-419", level: 3, label: "过失泄露国家秘密罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "过失泄露国家秘密罪"], chapterIndex: 9, itemIndex: 419 },
  { id: "criminal-l3-9-0-420", level: 3, label: "徇私枉法罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "徇私枉法罪"], chapterIndex: 9, itemIndex: 420 },
  { id: "criminal-l3-9-0-421", level: 3, label: "民事、行政枉法裁判罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "民事、行政枉法裁判罪"], chapterIndex: 9, itemIndex: 421 },
  { id: "criminal-l3-9-0-422", level: 3, label: "执行判决、裁定失职罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "执行判决、裁定失职罪"], chapterIndex: 9, itemIndex: 422 },
  { id: "criminal-l3-9-0-423", level: 3, label: "执行判决、裁定滥用职权罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "执行判决、裁定滥用职权罪"], chapterIndex: 9, itemIndex: 423 },
  { id: "criminal-l3-9-0-424", level: 3, label: "枉法仲裁罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "枉法仲裁罪"], chapterIndex: 9, itemIndex: 424 },
  { id: "criminal-l3-9-0-425", level: 3, label: "私放在押人员罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "私放在押人员罪"], chapterIndex: 9, itemIndex: 425 },
  { id: "criminal-l3-9-0-426", level: 3, label: "失职致使在押人员脱逃罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "失职致使在押人员脱逃罪"], chapterIndex: 9, itemIndex: 426 },
  { id: "criminal-l3-9-0-427", level: 3, label: "徇私舞弊减刑、假释、暂予监外执行罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "徇私舞弊减刑、假释、暂予监外执行罪"], chapterIndex: 9, itemIndex: 427 },
  { id: "criminal-l3-9-0-428", level: 3, label: "徇私舞弊不移交刑事案件罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "徇私舞弊不移交刑事案件罪"], chapterIndex: 9, itemIndex: 428 },
  { id: "criminal-l3-9-0-429", level: 3, label: "滥用管理公司、证券职权罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "滥用管理公司、证券职权罪"], chapterIndex: 9, itemIndex: 429 },
  { id: "criminal-l3-9-0-430", level: 3, label: "徇私舞弊不征、少征税款罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "徇私舞弊不征、少征税款罪"], chapterIndex: 9, itemIndex: 430 },
  { id: "criminal-l3-9-0-431", level: 3, label: "徇私舞弊发售发票、抵扣税款、出口退税罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "徇私舞弊发售发票、抵扣税款、出口退税罪"], chapterIndex: 9, itemIndex: 431 },
  { id: "criminal-l3-9-0-432", level: 3, label: "违法提供出口退税凭证罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "违法提供出口退税凭证罪"], chapterIndex: 9, itemIndex: 432 },
  { id: "criminal-l3-9-0-433", level: 3, label: "国家机关工作人员签订、履行合同失职被骗罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "国家机关工作人员签订、履行合同失职被骗罪"], chapterIndex: 9, itemIndex: 433 },
  { id: "criminal-l3-9-0-434", level: 3, label: "违法发放林木采伐许可证罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "违法发放林木采伐许可证罪"], chapterIndex: 9, itemIndex: 434 },
  { id: "criminal-l3-9-0-435", level: 3, label: "环境监管失职罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "环境监管失职罪"], chapterIndex: 9, itemIndex: 435 },
  { id: "criminal-l3-9-0-436", level: 3, label: "食品、药品监管渎职罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "食品、药品监管渎职罪"], chapterIndex: 9, itemIndex: 436 },
  { id: "criminal-l3-9-0-437", level: 3, label: "传染病防治失职罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "传染病防治失职罪"], chapterIndex: 9, itemIndex: 437 },
  { id: "criminal-l3-9-0-438", level: 3, label: "非法批准征收、征用、占用土地罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "非法批准征收、征用、占用土地罪"], chapterIndex: 9, itemIndex: 438 },
  { id: "criminal-l3-9-0-439", level: 3, label: "非法低价出让国有土地使用权罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "非法低价出让国有土地使用权罪"], chapterIndex: 9, itemIndex: 439 },
  { id: "criminal-l3-9-0-440", level: 3, label: "放纵走私罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "放纵走私罪"], chapterIndex: 9, itemIndex: 440 },
  { id: "criminal-l3-9-0-441", level: 3, label: "商检徇私舞弊罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "商检徇私舞弊罪"], chapterIndex: 9, itemIndex: 441 },
  { id: "criminal-l3-9-0-442", level: 3, label: "商检失职罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "商检失职罪"], chapterIndex: 9, itemIndex: 442 },
  { id: "criminal-l3-9-0-443", level: 3, label: "动植物检疫徇私舞弊罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "动植物检疫徇私舞弊罪"], chapterIndex: 9, itemIndex: 443 },
  { id: "criminal-l3-9-0-444", level: 3, label: "动植物检疫失职罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "动植物检疫失职罪"], chapterIndex: 9, itemIndex: 444 },
  { id: "criminal-l3-9-0-445", level: 3, label: "放纵制售伪劣商品犯罪行为罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "放纵制售伪劣商品犯罪行为罪"], chapterIndex: 9, itemIndex: 445 },
  { id: "criminal-l3-9-0-446", level: 3, label: "办理偷越国（边）境人员出入境证件罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "办理偷越国（边）境人员出入境证件罪"], chapterIndex: 9, itemIndex: 446 },
  { id: "criminal-l3-9-0-447", level: 3, label: "放行偷越国（边）境人员罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "放行偷越国（边）境人员罪"], chapterIndex: 9, itemIndex: 447 },
  { id: "criminal-l3-9-0-448", level: 3, label: "不解救被拐卖、绑架妇女、儿童罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "不解救被拐卖、绑架妇女、儿童罪"], chapterIndex: 9, itemIndex: 448 },
  { id: "criminal-l3-9-0-449", level: 3, label: "阻碍解救被拐卖、绑架妇女、儿童罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "阻碍解救被拐卖、绑架妇女、儿童罪"], chapterIndex: 9, itemIndex: 449 },
  { id: "criminal-l3-9-0-450", level: 3, label: "帮助犯罪分子逃避处罚罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "帮助犯罪分子逃避处罚罪"], chapterIndex: 9, itemIndex: 450 },
  { id: "criminal-l3-9-0-451", level: 3, label: "招收公务员、学生徇私舞弊罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "招收公务员、学生徇私舞弊罪"], chapterIndex: 9, itemIndex: 451 },
  { id: "criminal-l3-9-0-452", level: 3, label: "失职造成珍贵文物损毁、流失罪", parentId: "criminal-l1-9", path: ["刑事案由", "渎职罪", "失职造成珍贵文物损毁、流失罪"], chapterIndex: 9, itemIndex: 452 },
  { id: "criminal-l1-10", level: 1, label: "军人违反职责罪", parentId: null, path: ["刑事案由", "军人违反职责罪"], chapterIndex: 10 },
  { id: "criminal-l3-10-0-453", level: 3, label: "战时违抗命令罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "战时违抗命令罪"], chapterIndex: 10, itemIndex: 453 },
  { id: "criminal-l3-10-0-454", level: 3, label: "隐瞒、谎报军情罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "隐瞒、谎报军情罪"], chapterIndex: 10, itemIndex: 454 },
  { id: "criminal-l3-10-0-455", level: 3, label: "拒传、假传军令罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "拒传、假传军令罪"], chapterIndex: 10, itemIndex: 455 },
  { id: "criminal-l3-10-0-456", level: 3, label: "投降罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "投降罪"], chapterIndex: 10, itemIndex: 456 },
  { id: "criminal-l3-10-0-457", level: 3, label: "战时临阵脱逃罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "战时临阵脱逃罪"], chapterIndex: 10, itemIndex: 457 },
  { id: "criminal-l3-10-0-458", level: 3, label: "擅离、玩忽军事职守罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "擅离、玩忽军事职守罪"], chapterIndex: 10, itemIndex: 458 },
  { id: "criminal-l3-10-0-459", level: 3, label: "阻碍执行军事职务罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "阻碍执行军事职务罪"], chapterIndex: 10, itemIndex: 459 },
  { id: "criminal-l3-10-0-460", level: 3, label: "指使部属违反职责罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "指使部属违反职责罪"], chapterIndex: 10, itemIndex: 460 },
  { id: "criminal-l3-10-0-461", level: 3, label: "违令作战消极罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "违令作战消极罪"], chapterIndex: 10, itemIndex: 461 },
  { id: "criminal-l3-10-0-462", level: 3, label: "拒不救援友邻部队罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "拒不救援友邻部队罪"], chapterIndex: 10, itemIndex: 462 },
  { id: "criminal-l3-10-0-463", level: 3, label: "军人叛逃罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "军人叛逃罪"], chapterIndex: 10, itemIndex: 463 },
  { id: "criminal-l3-10-0-464", level: 3, label: "非法获取军事秘密罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "非法获取军事秘密罪"], chapterIndex: 10, itemIndex: 464 },
  { id: "criminal-l3-10-0-465", level: 3, label: "为境外窃取、剌探、收买、非法提供军事秘密罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "为境外窃取、剌探、收买、非法提供军事秘密罪"], chapterIndex: 10, itemIndex: 465 },
  { id: "criminal-l3-10-0-466", level: 3, label: "故意泄露军事秘密罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "故意泄露军事秘密罪"], chapterIndex: 10, itemIndex: 466 },
  { id: "criminal-l3-10-0-467", level: 3, label: "过失泄露军事秘密罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "过失泄露军事秘密罪"], chapterIndex: 10, itemIndex: 467 },
  { id: "criminal-l3-10-0-468", level: 3, label: "战时造谣惑众罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "战时造谣惑众罪"], chapterIndex: 10, itemIndex: 468 },
  { id: "criminal-l3-10-0-469", level: 3, label: "战时自伤罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "战时自伤罪"], chapterIndex: 10, itemIndex: 469 },
  { id: "criminal-l3-10-0-470", level: 3, label: "逃离部队罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "逃离部队罪"], chapterIndex: 10, itemIndex: 470 },
  { id: "criminal-l3-10-0-471", level: 3, label: "武器装备肇事罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "武器装备肇事罪"], chapterIndex: 10, itemIndex: 471 },
  { id: "criminal-l3-10-0-472", level: 3, label: "擅自改变武器装备编配用途罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "擅自改变武器装备编配用途罪"], chapterIndex: 10, itemIndex: 472 },
  { id: "criminal-l3-10-0-473", level: 3, label: "盗窃、抢夺武器装备、军用物资罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "盗窃、抢夺武器装备、军用物资罪"], chapterIndex: 10, itemIndex: 473 },
  { id: "criminal-l3-10-0-474", level: 3, label: "非法出卖、转让武器装备罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "非法出卖、转让武器装备罪"], chapterIndex: 10, itemIndex: 474 },
  { id: "criminal-l3-10-0-475", level: 3, label: "遗弃武器装备罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "遗弃武器装备罪"], chapterIndex: 10, itemIndex: 475 },
  { id: "criminal-l3-10-0-476", level: 3, label: "遗失武器装备罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "遗失武器装备罪"], chapterIndex: 10, itemIndex: 476 },
  { id: "criminal-l3-10-0-477", level: 3, label: "擅自出卖、转让军队房地产罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "擅自出卖、转让军队房地产罪"], chapterIndex: 10, itemIndex: 477 },
  { id: "criminal-l3-10-0-478", level: 3, label: "虐待部属罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "虐待部属罪"], chapterIndex: 10, itemIndex: 478 },
  { id: "criminal-l3-10-0-479", level: 3, label: "遗弃伤病军人罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "遗弃伤病军人罪"], chapterIndex: 10, itemIndex: 479 },
  { id: "criminal-l3-10-0-480", level: 3, label: "战时拒不救治伤病军人罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "战时拒不救治伤病军人罪"], chapterIndex: 10, itemIndex: 480 },
  { id: "criminal-l3-10-0-481", level: 3, label: "战时残害居民、掠夺居民财物罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "战时残害居民、掠夺居民财物罪"], chapterIndex: 10, itemIndex: 481 },
  { id: "criminal-l3-10-0-482", level: 3, label: "私放俘虏罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "私放俘虏罪"], chapterIndex: 10, itemIndex: 482 },
  { id: "criminal-l3-10-0-483", level: 3, label: "虐待俘虏罪", parentId: "criminal-l1-10", path: ["刑事案由", "军人违反职责罪", "虐待俘虏罪"], chapterIndex: 10, itemIndex: 483 }
];

export const CRIMINAL_CAUSE_LABEL_SET = new Set(CRIMINAL_CAUSE_LIBRARY.map((item) => item.label));

export const CRIMINAL_CAUSE_LEAF_LABEL_SET = new Set(
  CRIMINAL_CAUSE_LIBRARY.filter((item) => item.level === 3).map((item) => item.label),
);
